### ISSUE TITLE
Turtle is missing

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.thonny.Thonny#130]
I try

`import turtle`

I get

`ModuleNotFoundError: No module named 'turtle'`

**Comment by jwillikers** [comment]
`turtle` is not part of the base installation of Thonny. You'll need to install it inside the Flatpak through `Tools` > `Manage packages...`.

**Comment by firefoxlover** [comment]
is that gui way the same as `import` or `download`? because `import` doesnt work, which is the issue

**Comment by jwillikers** [comment]
@firefoxlover You need to install the package that way through the Gui before you can import it in your code with the `import` statement.

**Comment by jwillikers** [comment]
I believe I should have this fixed in #149.
