### ISSUE TITLE
pip install in Flatpak container doesnt work

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.thonny.Thonny#148]
I know Thonny has a GUI to install python libs, but I wonder why it doesnt work to install them via pip?

```
flatpak enter org.thonny.Thonny sh
pip install pySimpleGui
```

Doesnt show up, even though you can find it under `~/.var/app/org.thonny.Thonny/lib/python3` or a similar directory

Why is that, is there a problem occuring for some libs, is there a workaround?

**Comment by jwillikers** [comment]
Thanks for submitting this issue. You are right that it isn't finding packages installed with `pip`. Something must be slightly off with the `PYTHONPATH`. Right now, I think it should be using packages installed in `~/.local/lib/python3.10/site-packages` and should be installing there with `pip`. This is probably a side effect of changing permissions to allow home directory access to make accessing and running scripts less problematic from inside the sandbox.

However, I should probably configure the Flatpak to use the directories under `~/.var/app/org.thonny.Thonny/` to maintain better isolation from the host system.

For now, you should be able to use a virtual environment through Thonny's Interpreter configuration and use pip in that virtual environment. Sorry for the trouble!

**Comment by jwillikers** [comment]
@firefoxlover #149 should fix this.
