### ISSUE TITLE
Qt: Session management error: Could not open network socket on Thonny flatpak version

### ISSUE THREAD

**Issue by Davidm16** [flathub/org.thonny.Thonny#261]
I am trying to cap a webcam with opencv and the error "Qt: Session management error: Could not open network socket" appears only in this flatpak version

**Comment by jwillikers** [comment]
Qt 5 or 6?

**Comment by Davidm16** [comment]
I don’t know, it appears when running a camera demo

**Comment by jwillikers** [comment]
Hmm, I found a fix for another Flatpak that appears to be related [here](https://github.com/flathub/com.vzhd1701.gridplayer/blob/8d53425bef6a235203f751d63e777ec1a207a764/com.vzhd1701.gridplayer.yml#L23-L25).

@Davidm16 Can you try running the Flatpak on command-line with the flag `--env=SESSION_MANAGER=`.

```
flatpak run --env=SESSION_MANAGER= org.thonny.Thonny
```

**Comment by Davidm16** [comment]
Qt: Session management error: networkIdsList argument is NULL
